
# Project
group=com.tristankechlo.livingthings

# Common
java_version=21
minecraft_version=1.21.7
version_range=[1.21.7,1.21.8)
auto_service_version=1.1.1

# Forge
forge_version=57.0.3
forge_loader_range=[57,)

# Fabric
fabric_version=0.129.0+1.21.7
fabric_loader_version=0.16.14
fabric_loader_min=0.16
fabric_range_min_inclusive=1.21.7
fabric_range_max_exclusive=1.21.8

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.7.25-beta
neoforge_loader_range=[4,)
neoforge_range=[21.7,)

# Mod options
mod_name=LivingThings
mod_author=Buecher_wurm
mod_id=livingthings
mod_version=2.3.0

# Other Mods
modmenu_version=15.0.0

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.7-20250711.194848

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.7
parchment_version=2025.07.18

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
