
# Project
group=com.tristankechlo.livingthings

# Common
java_version=21
minecraft_version=1.21.4
version_range=[1.21.4,1.21.5)
auto_service_version=1.1.1

# Forge
forge_version=54.1.0
forge_loader_range=[54,)

# Fabric
fabric_version=0.119.3+1.21.4
fabric_loader_version=0.16.14
fabric_loader_min=0.16
fabric_range_min_inclusive=1.21.4
fabric_range_max_exclusive=1.21.5

# NeoForge
neoforge_version=21.4.138
neoforge_loader_range=[4,)
neoforge_range=[21.4,)

# Mod options
mod_name=LivingThings
mod_author=Buecher_wurm
mod_id=livingthings
mod_version=2.3.0

# Other Mods
modmenu_version=13.0.3

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.4-20241203.161809

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.4
parchment_version=2025.03.23

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
